/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import Class.DBHELPER;
import static Class.DBHELPER.ppData;
import Class.USER;
import Class.select;
import com.sun.org.apache.xpath.internal.operations.Bool;
import java.awt.Image;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import static java.lang.System.exit;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.commons.dbutils.DbUtils;

/**
 *
 * @author Ehsan
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    DefaultTableModel model;
    DefaultTableModel model2;
    int TOTALSALARY=0;
    String CLUBNAME;
    int min = 100000;
    int max = -1;
    int TOTALCOACH =0;
     Market_page marketobj = new Market_page();
      Match_schedule_page matchobj = new Match_schedule_page();
      Settings_page settingobj = new Settings_page();
      squard2_formation squadobj = new squard2_formation();
    public Homepage() {
        initComponents();
        CLUBNAME = jLabel3.getText();
                       Image icon7 = new ImageIcon(this.getClass().getResource("/Logo.jpeg")).getImage();
                       
       this.setIconImage(icon7);
       this.setTitle("Football Manager");
        From_TextField.setVisible(false);
                To_TextField.setVisible(false);
                jTextField2.setVisible(false);
                        jComboBox1.setVisible(false);
                        jLabel7.setVisible(false);
                                jLabel5.setVisible(false);
                                jButton9.setVisible(false);
                                        jLabel6.setVisible(false);
                                                jLabel8.setVisible(false);
                                                jLabel8.setVisible(false);
                                                jLabel19.setVisible(false);
                                                jTextField12.setVisible(false);
                                                jComboBox1.setVisible(false);
                                                jButton18.setVisible(false);                                            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        To_TextField = new javax.swing.JTextField();
        From_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabDS = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 37, 37));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(270, 635));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 235));
        jLabel1.setText("MANAGER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 160, 58));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 250, 235));
        jLabel2.setText("FOOTBALL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 58));

        jButton1.setBackground(new java.awt.Color(37, 37, 37));
        jButton1.setFont(new java.awt.Font("Source Serif Pro", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-stadium-50.png"))); // NOI18N
        jButton1.setText("Squad Formation");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 372, 270, 40));

        jButton2.setBackground(new java.awt.Color(37, 37, 37));
        jButton2.setFont(new java.awt.Font("Source Serif Pro", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/image4.png"))); // NOI18N
        jButton2.setText(" Home");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 270, 50));

        jButton3.setBackground(new java.awt.Color(37, 37, 37));
        jButton3.setFont(new java.awt.Font("Source Serif Pro", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/market2.png"))); // NOI18N
        jButton3.setText(" Market");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 50));

        jButton4.setBackground(new java.awt.Color(37, 37, 37));
        jButton4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logt.png"))); // NOI18N
        jButton4.setText(" Log Out");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 270, 60));

        jButton5.setBackground(new java.awt.Color(37, 37, 37));
        jButton5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/settings2.png"))); // NOI18N
        jButton5.setText(" Settings");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 270, 50));

        jButton11.setBackground(new java.awt.Color(37, 37, 37));
        jButton11.setFont(new java.awt.Font("Source Serif Pro", 1, 20)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendar-icon-in-trendy-flat-style-isolated-on-grey-background-calendar-symbol-design-logo-app-ui-vector-illustration-2A24EKG.jpg"))); // NOI18N
        jButton11.setText("Match Schedule");
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(37, 37, 37));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 635));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 250, 235));
        jLabel4.setText("             Search By >");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 40));

        jButton6.setBackground(new java.awt.Color(37, 37, 37));
        jButton6.setFont(new java.awt.Font("Caladea", 1, 17)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("SALARY RANGE");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 40));

        jButton7.setBackground(new java.awt.Color(37, 37, 37));
        jButton7.setFont(new java.awt.Font("Caladea", 1, 17)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("NAME");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 30));

        jButton8.setBackground(new java.awt.Color(37, 37, 37));
        jButton8.setFont(new java.awt.Font("Caladea", 1, 17)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("POSITION");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 40));

        jButton12.setBackground(new java.awt.Color(37, 37, 37));
        jButton12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Max Salary");
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 30));

        jButton13.setBackground(new java.awt.Color(37, 37, 37));
        jButton13.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Max Age");
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 30));

        jButton14.setBackground(new java.awt.Color(37, 37, 37));
        jButton14.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Max Height");
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusPainted(false);
        jButton14.setFocusable(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 30));

        jButton15.setBackground(new java.awt.Color(37, 37, 37));
        jButton15.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Country-wise Player Count");
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setFocusPainted(false);
        jButton15.setFocusable(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 200, 30));

        jButton16.setBackground(new java.awt.Color(37, 37, 37));
        jButton16.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("Total Salary");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusPainted(false);
        jButton16.setFocusable(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 200, 30));

        jButton17.setBackground(new java.awt.Color(37, 37, 37));
        jButton17.setFont(new java.awt.Font("Caladea", 1, 17)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("COUNTRY");
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 40));

        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 200, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel3.setText("Manchester United");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 270, 40));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search2.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 40, 40));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton10.setText("Update");
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 100, 30));

        To_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_TextFieldActionPerformed(evt);
            }
        });
        To_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                To_TextFieldKeyReleased(evt);
            }
        });
        jPanel1.add(To_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 80, 30));

        From_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                From_TextFieldActionPerformed(evt);
            }
        });
        From_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                From_TextFieldKeyReleased(evt);
            }
        });
        jPanel1.add(From_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 80, 30));

        jLabel5.setText("TO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Position", "CF", "LWF", "RWF", "AMF", "CMF", "DML", "LMF", "RMF", "LB", "RB", "CB", "GK" }));
        jComboBox1.setName("Select Position"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 160, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Caladea", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Notification");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 480, 20));

        jLabel7.setText("FROM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 2, 19)); // NOI18N
        jLabel8.setText("You don't have any coach");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 210, 30));

        jTabDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Coach", "Renewable", "Salary"
            }
        ));
        jTabDS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabDSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTabDS);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 620, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel9.setText("Position :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 100, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel11.setText("Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 80, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel12.setText("Club :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 110, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel13.setText("Age :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 110, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel14.setText("Country :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 110, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel15.setText("Height :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 90, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel16.setText("Salary :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 90, 40));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 170, 40));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 170, 40));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 170, 40));

        jLabel19.setText("Invalid Position");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 90, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 170, 40));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 170, 40));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 170, 40));

        jTextField10.setEditable(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 170, 40));

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton19.setText("Add");
        jButton19.setFocusable(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 100, 30));

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton20.setText("Edit");
        jButton20.setFocusable(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 100, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Renewable :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 90, 40));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 170, 40));

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton21.setText("Sell");
        jButton21.setFocusable(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Country", "Position", "Renewable", "Age", "Height", "Salary"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Position");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Age");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Height");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Salary");
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 620, 120));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 2, 21)); // NOI18N
        jLabel18.setText("Sorry. No Player Found ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 210, 30));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 160, 40));

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton18.setText("Done");
        jButton18.setFocusable(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        setBounds(140, 30, 1106, 643);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        marketobj.setVisible(false);
        settingobj.setVisible(false);
        matchobj.setVisible(false);
        squadobj.passValue(jLabel3.getText());
        squadobj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        marketobj.setVisible(false);
        squadobj.setVisible(false);
        settingobj.setVisible(false);
        matchobj.setVisible(false);
        textFiledEmpty();
        jComboBox1.setVisible(false);
        jTextField12.setVisible(false);
        
        To_TextField.setVisible(false);
        From_TextField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        
        jTextField2.setVisible(false);
        jButton9.setVisible(false);
        jLabel6.setVisible(false);
        jLabel6.setVisible(false);
        lol();
        int p =TOTALCOACH+TOTALSALARY;
        jButton16.setText("Total Salary: "+p);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       matchobj.setVisible(false);
        squadobj.setVisible(false);
        settingobj.setVisible(false);
        marketobj.passValue(jLabel3.getText());
        marketobj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int input = JOptionPane.showConfirmDialog(this, "Confirm LogOut! ?",  "Select an Option...",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(input == 0){
        setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        marketobj.setVisible(false);
        squadobj.setVisible(false);
        matchobj.setVisible(false);
        settingobj.passValue(jLabel3.getText());
        settingobj.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
                To_TextField.setVisible(true);
        From_TextField.setVisible(true);
        jLabel5.setVisible(true);
        jLabel7.setVisible(true);
        jComboBox1.setVisible(false);
        jTextField12.setVisible(false);
        jTextField2.setVisible(false);
        jButton9.setVisible(true);
        
        lol2();  
        
        From_TextField.setText(""+min);
        To_TextField.setText(""+max);
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
        jComboBox1.setVisible(false);
        jTextField12.setVisible(false);
        
        To_TextField.setVisible(false);
        From_TextField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        
        jTextField2.setVisible(true);
        jButton9.setVisible(true);
        jLabel6.setVisible(false);
        jLabel6.setVisible(false);
        lol();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
        jComboBox1.setVisible(true);
        jTextField12.setVisible(false);
                To_TextField.setVisible(false);
        From_TextField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        jTextField2.setVisible(false);
        jButton9.setVisible(false);
        jButton9.setVisible(true);
       lol();
    }//GEN-LAST:event_jButton8ActionPerformed
public void textFiledEmpty()
{
        jTextField5.setText("");
        jTextField10.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField11.setText("");
        
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField4.setText("");
}
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
                 int row = 0;
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"No Player In the Table");
                return;
            }
         int maxsalary=-1;
         int row_max = 0;
        for(row=0;row < model.getRowCount() ; row++)
        {
            int SALARY = Integer.parseInt(model.getValueAt(row, 6).toString());
            if(SALARY>maxsalary){
                maxsalary = SALARY;
                row_max = row;
            }
        }
            
        jTextField5.setText(model.getValueAt(row_max, 0).toString());
        jTextField10.setText(jLabel3.getText());
        jTextField6.setText(model.getValueAt(row_max, 1).toString());
        jTextField7.setText(model.getValueAt(row_max, 4).toString());
       if(model.getValueAt(row_max, 3).toString().equals("1"))
       {
           jTextField11.setText("Yes");
       }
       else
       {
           jTextField11.setText("No");
       }
        
        jTextField8.setText(model.getValueAt(row_max, 5).toString());
        jTextField9.setText(model.getValueAt(row_max, 6).toString());
        jTextField4.setText(model.getValueAt(row_max, 2).toString()) ;

        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
         int row = 0;
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"No Player In the Table");
                return;
            }
         int maxage=-1;
         int row_max = 0;
        for(row=0;row < model.getRowCount() ; row++)
        {
            int AGE = Integer.parseInt(model.getValueAt(row, 4).toString());
            if(AGE>maxage){
                maxage = AGE;
                row_max = row;
            }
        }
            
        jTextField5.setText(model.getValueAt(row_max, 0).toString());
        jTextField10.setText(jLabel3.getText());
        jTextField6.setText(model.getValueAt(row_max, 1).toString());
        jTextField7.setText(model.getValueAt(row_max, 4).toString());
       if(model.getValueAt(row_max, 3).toString().equals("1"))
       {
           jTextField11.setText("Yes");
       }
       else
       {
           jTextField11.setText("No");
       }
        
        jTextField8.setText(model.getValueAt(row_max, 5).toString());
        jTextField9.setText(model.getValueAt(row_max, 6).toString());
        jTextField4.setText(model.getValueAt(row_max, 2).toString()) ;
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
        textFiledEmpty();
         int row = 0;
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"No Player In the Table");
                return;
            }
         float maxsalary = -1;
         int row_max = 0;
        for(row=0;row < model.getRowCount() ; row++)
        {
            float SALARY = Float.parseFloat(model.getValueAt(row, 5).toString());
            if(SALARY>maxsalary){
                maxsalary = SALARY;
                row_max = row;
            }
        }
            
        jTextField5.setText(model.getValueAt(row_max, 0).toString());
        jTextField10.setText(jLabel3.getText());
        jTextField6.setText(model.getValueAt(row_max, 1).toString());
        jTextField7.setText(model.getValueAt(row_max, 4).toString());
       if(model.getValueAt(row_max, 3).toString().equals("1"))
       {
           jTextField11.setText("Yes");
       }
       else
       {
           jTextField11.setText("No");
       }
        
        jTextField8.setText(model.getValueAt(row_max, 5).toString());
        jTextField9.setText(model.getValueAt(row_max, 6).toString());
        jTextField4.setText(model.getValueAt(row_max, 2).toString()) ;

               
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         textFiledEmpty();
         int row = 0;
            if(model.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"No Player In the Table");
                return;
            }
         int cou = -1;
         HashMap <String,Integer> mp = new HashMap<>();
        for(row=0;row < model.getRowCount() ; row++)
        {
            String COUNTRY = model.getValueAt(row, 1).toString();
             if(mp.get(COUNTRY)==null){
                 mp.put(COUNTRY,1);
             }
             else{
                  int t=mp.get(COUNTRY);
                 t++;
                 mp.put(COUNTRY,t);
             }            
           // System.out.println("mp"+ mp.get(COUNTRY));
            //mp. put(COUNTRY, (mp.get(COUNTRY).intValue())+1 ); 
        }
        PopUpFor_Country_wise_player_count obj = new PopUpFor_Country_wise_player_count();
        obj.pass(mp);
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        textFiledEmpty();
        jComboBox1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField12.setVisible(true);
                To_TextField.setVisible(false);
        From_TextField.setVisible(false);
        jLabel5.setVisible(false);
        jLabel7.setVisible(false);
        jButton9.setVisible(true);
        jLabel6.setVisible(false);
        lol();
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void To_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_TextFieldActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void From_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_From_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_From_TextFieldActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        marketobj.setVisible(false);
        squadobj.setVisible(false);
        settingobj.setVisible(false);
       matchobj.passValue(jLabel3.getText());
        matchobj.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    public void lol()
    {
        jComboBox1.setSelectedItem("Position");
        String cnm = jLabel3.getText();
        String position =  "";
        TOTALSALARY = 0;
            jLabel18.setVisible(false); 
            int check =0;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
                
                
                
              ResultSet rs = DBHELPER.posData(position,CLUBNAME);

                
                
                
                while(rs.next()){
                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                     TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                    }
                  }
                }
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
                int p = TOTALCOACH + TOTALSALARY;
                jButton16.setText("Total Salary: "+TOTALSALARY);
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void lol2()
    {
        jComboBox1.setSelectedItem("Position");
        String cnm = jLabel3.getText();
        String position =  "";
        TOTALSALARY = 0;
            jLabel18.setVisible(false); 
            int check =0;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
              ResultSet rs = DBHELPER.posData(position,CLUBNAME);
                while(rs.next()){
                    if(rs.getString("clubName").equals(cnm)){
                                            TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    
                    int q = Integer.parseInt(rs.getString("Salary"));
                    if(min>q)
                    min = q;
                    if(max<q)
                    max = q;
                    v.add(rs.getString("Salary"));

                    dtm.addRow(v);
                    }
                }
                jButton16.setText("Total Salary: "+TOTALSALARY);
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String position =  jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String cnm = jLabel3.getText();
        TOTALSALARY = 0;
        if(!position.equals("Position")){
            jLabel18.setVisible(false); 
            int check =0;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
                ResultSet rs = DBHELPER.posData(position,CLUBNAME);
                while(rs.next()){
                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                         TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                        check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                        }
                    }
                }
                jButton16.setText("Total Salary: "+TOTALSALARY );
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
        }
        else{
            lol();
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTabDSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabDSMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jTabDSMouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed
public void initNull(){
    jTextField5.setText("");
            jTextField10.setText("");
    jTextField6.setText("");
            jTextField7.setText("");
            jTextField11.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                            jTextField4.setText("");
}
public void disableAll()
{
    jButton7.setEnabled(false);
    jButton8.setEnabled(false);
    jButton17.setEnabled(false);
    jButton6.setEnabled(false);
    jButton13.setEnabled(false);
    jButton12.setEnabled(false);
    jButton14.setEnabled(false);
    jButton15.setEnabled(false);
}
public void enableAll()
{
    jButton7.setEnabled(true);
    jButton8.setEnabled(true);
    jButton17.setEnabled(true);
    jButton6.setEnabled(true);
    jButton13.setEnabled(true);
    jButton12.setEnabled(true);
    jButton14.setEnabled(true);
    jButton15.setEnabled(true);
}
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if(jTextField5.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter New Player Info"); 
            jTextField5.setEditable(true);
            turnOn();
            jButton18.setVisible(true);
            jButton21.setVisible(false);
                    jButton20.setVisible(false);
                    jButton10.setVisible(false);
                    jTextField10.setText(jLabel3.getText());
                    disableAll();
        }
        else{
            JOptionPane.showMessageDialog(this, "Player Already added. Type New Player Info");   
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed
    
    public void turnOn()
    {
        jTextField4.setEditable(true);
        jTextField6.setEditable(true);
        jTextField7.setEditable(true);
        jTextField8.setEditable(true);
        jTextField11.setEditable(true);
        jTextField9.setEditable(true);
        jTable1.setEnabled(false);
    }
        public void turnOff()
    {
        jTextField4.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField11.setEditable(false);
        jTextField9.setEditable(false);
        jTable1.setEnabled(true);
    }
    
    
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
       turnOn();
        JOptionPane.showMessageDialog(this,"You can now edit field");

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        String temp = jTextField5.getText();
        if(temp.isEmpty())
        {
            jLabel6.setText("Select A Row To Operate");
            jLabel6.setVisible(true);
            return;
        }
        Player_Sell_Page obj = new Player_Sell_Page();
        String name = jTextField5.getText();
             String clubname =  jTextField10.getText();
            String countryname = jTextField6.getText();
                    String Age_now =  jTextField7.getText();
                            String Height_now  =  jTextField8.getText();
                            String Salary_now  =  jTextField9.getText();
                            String position_now =  jTextField4.getText();
        
        obj.passValues(this,name,clubname,countryname,Age_now,Height_now,Salary_now,position_now);
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton21ActionPerformed

    public void DOTABLE2() throws SQLException
    {
        TOTALCOACH =0;
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql2 = "select * from coach_details where clubName = ?";
            PreparedStatement plat2 = c.prepareStatement(sql2);
            plat2.setString(1, jLabel3.getText());
            ResultSet rs2 = plat2.executeQuery();
            model2 = (DefaultTableModel)jTabDS.getModel();
            model2.setRowCount(0);
            int check2 =0;
            
            while(rs2.next()){
                check2 = 1;
                TOTALCOACH  = TOTALCOACH +  rs2.getInt("salary");
                 String[] std = new String[] {rs2.getString(1), rs2.getString(3), rs2.getString(4)} ;
                 model2.addRow( std);
                 jLabel8.setVisible(false);
            }
            if(check2 ==0)
            {
                jLabel8.setVisible(true);
            }
            plat2.close();
            c.close();
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            
            // TODO add your handling code here:
             Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where clubName = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, jLabel3.getText());

            ResultSet rs = plat.executeQuery();
            
            model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            int check =0;
            
            while(rs.next()){
                if(rs.getString("market_status").equals("0")){
                check = 1;
                 TOTALSALARY  = TOTALSALARY +  rs.getInt("Salary");
                 String[] std = new String[] {rs.getString(1), rs.getString(3), rs.getString(4), rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8) } ;
                 model.addRow( std);
                 jLabel18.setVisible(false);
                }
            }
            if(check ==0)
            {
                jLabel18.setVisible(true);
            }
            plat.close();
           DOTABLE2();
           int p = TOTALSALARY+TOTALCOACH;
            jButton16.setText("Total Salary: "+p);
            
           // JOptionPane.showMessageDialog(this,"Data Viewed");
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown
    
    public void search(String str)
    {
        jLabel18.setVisible(false);
         model = (DefaultTableModel)jTable1.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
         jTable1.setRowSorter(trs);
         trs.setRowFilter(RowFilter.regexFilter(str));
         try{
             String pogba = jTable1.getValueAt(0, 0).toString();
         if(pogba.isEmpty())
                {
                     jLabel18.setVisible(true);
                }
                 else
                {
                     jLabel18.setVisible(false);
                }
            }
         catch(Exception e){
             jLabel18.setVisible(true);
         }
    }
    
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        
            // TODO add your handling code here:
         
               jLabel18.setVisible(false);
            String searchSTN = jTextField2.getText();
            int check =0;
            TOTALSALARY = 0;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
                
                ResultSet rs = DBHELPER.petData(searchSTN,CLUBNAME);
                String cnm = jLabel3.getText();
                
                while(rs.next()){
                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                        TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                        }
                    }
                }
                jButton16.setText("Total Salary: "+TOTALSALARY);
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        
            int row = jTable1.getSelectedRow();
            if(model.getRowCount() == 0){
                model = (DefaultTableModel)jTable1.getModel();
            }
            System.out.println(""+row);
        jTextField5.setText(model.getValueAt(row, 0).toString());
        jTextField10.setText(jLabel3.getText());
        jTextField6.setText(model.getValueAt(row, 1).toString());
        jTextField7.setText(model.getValueAt(row, 4).toString());
       if(model.getValueAt(row, 3).toString().equals("1"))
       {
           jTextField11.setText("Yes");
       }
       else
       {
           jTextField11.setText("No");
       }
        
        jTextField8.setText(model.getValueAt(row, 5).toString());
        jTextField9.setText(model.getValueAt(row, 6).toString());
        jTextField4.setText(model.getValueAt(row, 2).toString()) ;   
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String query = "update player_details set country = ? , position= ? , player_status= ? , age = ? , Height = ? , Salary = ? where Name= ?";
            PreparedStatement plat = c.prepareStatement(query);
            
              Boolean player_statussd = false;
              int ppop = 0;
                if(jTextField11.getText().equals("Yes"))
                {
                    player_statussd = true;
                    ppop = 1;
                }
            
            plat.setString(1,jTextField6.getText());
            plat.setString(2,jTextField4.getText());
            plat.setBoolean(3,player_statussd);
            plat.setInt(4,Integer.parseInt(jTextField7.getText()));
            plat.setFloat(5,Float.parseFloat(jTextField8.getText()));
            plat.setInt(6,Integer.parseInt(jTextField9.getText()));
            plat.setString(7,jTextField5.getText());
            plat.executeUpdate();
            model = (DefaultTableModel) jTable1.getModel();
            if(jTable1.getSelectedRowCount() == 1)
            {
                String countrys = jTextField6.getText();
                String positions = jTextField4.getText();
                String player_statuss = jTextField11.getText();
                String ages = jTextField7.getText();
                String heightss = jTextField8.getText();
                String salarys = jTextField9.getText();
                
                model.setValueAt(countrys, jTable1.getSelectedRow(), 1);
                model.setValueAt(positions, jTable1.getSelectedRow(), 2);
                model.setValueAt(ppop , jTable1.getSelectedRow(), 3);
                model.setValueAt(ages, jTable1.getSelectedRow(), 4);
                model.setValueAt(heightss, jTable1.getSelectedRow(), 5);
                model.setValueAt(salarys, jTable1.getSelectedRow(), 6);
            }
            
            JOptionPane.showMessageDialog(this,"Data Updated");
            jTable1.setEnabled(true);
            c.close();
            plat.close();
            turnOff();
        } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        jLabel19.setVisible(false);
        String jstd = jTextField4.getText();
        if(jstd.equals(""))
        {
            jLabel19.setVisible(false);
        }
        else{
        if(jstd.equals("CF"))
        {
            jLabel19.setVisible(false);
        }
        else
        {
            if(jstd.equals("LWF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("RWF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("AMF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("CMF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("DML"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("LMF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("RMF"))
            {
                jLabel19.setVisible(false);
            }
            else{
                if(jstd.equals("LB"))
            {
                jLabel19.setVisible(false);
            }
            else{
                                if(jstd.equals("RB"))
            {
                jLabel19.setVisible(false);
            }
            else{
                                if(jstd.equals("CB"))
            {
                jLabel19.setVisible(false);
            }
            else{
                                if(jstd.equals("GK"))
            {
                jLabel19.setVisible(false);
            }
            else{
                jLabel19.setVisible(true);
            }
            }
            }
            }
            }
            }
            }
            }
            }
            }
            }
        }
    }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        // TODO add your handling code here:
        
            jLabel18.setVisible(false);
            String name = jTextField12.getText();
            String cnm = jLabel3.getText();
            int check =0;
            TOTALSALARY = 0;
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
                
                ResultSet rs = DBHELPER.getData(name,cnm);
                
                while(rs.next()){
                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                        TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                        }
                    }
                }
                jButton16.setText("Total Salary: "+TOTALSALARY);
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.out.println(CLUBNAME);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void From_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_From_TextFieldKeyReleased
        // TODO add your handling code here:
            jLabel18.setVisible(false);
            
            String st1 = From_TextField.getText();
            String st2 = To_TextField.getText();
            int jo = 0;
            int po = 0;
            try{
            jLabel6.setVisible(false);    
            jo = Integer.parseInt(st1);
            po = Integer.parseInt(st2);
             if(jo < min)
            {
                jLabel6.setText("Minimum Range Start from "+min);
                jLabel6.setVisible(true);                
            }
             else{
                 if(jo>po)
                 {
                jLabel6.setText("Minimum Range must be less than Maximum Range");
                jLabel6.setVisible(true); 
                 }
             }
            
            } catch (Exception ex)
            {
                jLabel6.setText("Please Input Numbers only");
                jLabel6.setVisible(true);
            }
            
            TOTALSALARY = 0;
//            String searchSTN = jTextField2.getText();
            int check =0;
//            
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
//               
                ResultSet rs = DBHELPER.ppData(jo,po,CLUBNAME);
                String cnm = jLabel3.getText();
//                
                while(rs.next()){

                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                    TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                        }
                    }
                }
                jButton16.setText("Total Salary: "+TOTALSALARY);
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_From_TextFieldKeyReleased

    private void To_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_To_TextFieldKeyReleased
        // TODO add your handling code here:
            jLabel18.setVisible(false);
            
            String st2 = To_TextField.getText();
            String st1 = From_TextField.getText();
            int jo = 1000000;
            int po = 1000000;
            try{
            jLabel6.setVisible(false);    
            po = Integer.parseInt(st2);
            jo = Integer.parseInt(st1);
             if(po > max)
            {
                jLabel6.setText("Maximum Range is "+max);
                jLabel6.setVisible(true);                
            }
            else{
                 if(po<jo)
                 {
                jLabel6.setText("Maximum Range must be than greater than Minimum Range");
                jLabel6.setVisible(true); 
                 }
             }
            
            } catch (Exception ex)
            {
                jLabel6.setText("Please Input Numbers only");
                jLabel6.setVisible(true);
            }
            TOTALSALARY = 0;
            
            
//            String searchSTN = jTextField2.getText();
            int check =0;
//            
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int r = jTable1.getRowCount();
            while( r-- > 0)
            {
                dtm.removeRow(r);
            }
            try{
//               
                ResultSet rs = DBHELPER.ppData(jo,po,CLUBNAME);
                String cnm = jLabel3.getText();
//                
                while(rs.next()){

                    if(rs.getString("clubName").equals(cnm)){
                        if(rs.getString("market_status").equals("0")){
                      TOTALSALARY = TOTALSALARY + rs.getInt("Salary");
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("country"));
                    v.add(rs.getString("position"));
                    v.add(rs.getString("player_status"));
                    v.add(rs.getString("age"));
                    v.add(rs.getString("Height"));
                    v.add(rs.getString("Salary"));

                   dtm.addRow(v);
                        }
                    }
                }
                jButton16.setText(""+TOTALSALARY);
                if(check == 0)
                {
                    jLabel18.setVisible(true);
                }
            } catch (SQLException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }            
            
            
    }//GEN-LAST:event_To_TextFieldKeyReleased

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
                                 int ok=0;
                            try {          
                                Connection cd = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                                String selectSQL = "SELECT * FROM player_details WHERE Name = ?";
                                PreparedStatement plater = cd.prepareStatement(selectSQL);
                                plater.setString(1, jTextField5.getText());
                                
                                // execute select SQL stetement
                                    ResultSet rs = plater.executeQuery();

                                        try {
                                           while (rs.next()) {
                                           String username = rs.getString("Name");
                                           jLabel6.setText(username + " Already Exist in the Database");
                                           jLabel6.setVisible(true);
                                             ok = 1;
                                             cd.close();
                                           plater.close();
                                           break;
                                          }
                                    } catch (SQLException e1) {
                                                Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, e1);
                                    }
                            }
                            catch (SQLException ex) {
                                 Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
                            }

                    if(ok==0){
                     try {
               Boolean player_statussd = false;
                if(jTextField11.getText().equals("Yes"))
                {
                    player_statussd = true;
                }
                            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                            String sql = "insert into player_details (Name,clubName , country,position,player_status,age,Height,Salary,market_status) values (?,?,?,?,?,?,?,?,?)";
                            PreparedStatement plat = c.prepareStatement(sql);
                                       plat.setString(1,jTextField5.getText());
                                        plat.setString(2,jTextField10.getText());                            
                            
                                       plat.setString(3,jTextField6.getText());
                                        plat.setString(4, jTextField4.getText());
                                         plat.setBoolean(5,player_statussd);
                                        plat.setInt(6,Integer.parseInt(jTextField7.getText()));
                                        plat.setFloat(7,Float.parseFloat(jTextField8.getText()));
                                        plat.setInt(8,Integer.parseInt(jTextField9.getText()));
                                        plat.setBoolean(9,false);
                                        plat.executeUpdate();
                                        JOptionPane.showMessageDialog(this,"Data inserted");
                                        c.close();
                                        plat.close();
                            jButton18.setVisible(false);
                            jTextField5.setEditable(false);
                            turnOff();
                            jButton21.setVisible(true);
                            jButton20.setVisible(true);
                            jButton10.setVisible(true);
                            enableAll();
                            lol();
                     }   catch (SQLException ex) {
                           Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField From_TextField;
    private javax.swing.JTextField To_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabDS;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables


    void passName(String s_name) {
        jLabel3.setText(s_name);
        //Image img = new ImageIcon(this.getClass().getResource("/ManULogo.png")).getImage();
        //jLabel10.setIcon(new ImageIcon(img));
        //ImageIcon image = new ImageIcon();
        //ImageIcon image = new ImageIcon(this.getClass().getResource();
        //jLabel10 = new JLabel(image);
//        ImageIcon image = new ImageIcon ("/ManULogo.png");
//        Image img = image.getImage();
//        Image newimg = img.getScaledInstance(jLabel10.getWidth(),jLabel10.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon imagess = new ImageIcon(newimg);
        
        
//        jLabel10.setIcon(imagess);
    }

    void RemovePlayerInfo(String text) {
        lol();
    }
}
