/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ehsan
 */
public class Match_schedule_page extends javax.swing.JFrame {

    /**
     * Creates new form Match_schedule_page
     */
    
     DefaultTableModel dtm;
    public Match_schedule_page() {
        initComponents();
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Club_name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 260, 50));

        jTable1.setBackground(new java.awt.Color(23, 40, 60));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Opposition Team", "Venue", "Date And Time"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(255, 0, 51));
        jTable1.setOpaque(false);
        jTable1.setShowGrid(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 730, 130));

        jButton1.setBackground(new java.awt.Color(156, 174, 136));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Add Match Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 190, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 40, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Sorry. No Schedule Added");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1637809.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(408, 60, 830, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // TODO add your handling code here:
             setVisible(false);
             Schedule_add obj = new Schedule_add();
             obj.setVisible(true);
             obj.passNamePAGE(jLabel1.getText());
             yelool();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
               try {
            jLabel2.setVisible(false);
            // TODO add your handling code here:
                    String HomeVENUE=""; 
                     String AwayVENUE="";                    
          Connection c2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                    String sql2="";
                    PreparedStatement plat2;
                    sql2 = "select * from clubdetails where Name = ?";     
                    plat2 = c2.prepareStatement(sql2);
                    plat2.setString(1,jLabel1.getText());
                    ResultSet rs2 = plat2.executeQuery();
                         while(rs2.next()){
                                HomeVENUE = rs2.getString("stadium");
                                 break;
                         }
                   System.out.println(""+HomeVENUE);            
            c2.close();
            plat2.close();
            
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from match_details where clubname = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1,jLabel1.getText());
            ResultSet rs = plat.executeQuery();
            
            dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
            int check =0;

                    while(rs.next()){
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("opponent"));
                    
                    String OPPONENT = rs.getString("opponent");
                    Connection cd2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                    String sqld2="";
                    PreparedStatement platd2;
                    sqld2 = "select * from clubdetails where Name = ?";     
                    platd2 = cd2.prepareStatement(sqld2);
                    platd2.setString(1,OPPONENT);
                    ResultSet rsd2 = platd2.executeQuery();
                         while(rsd2.next()){
                                AwayVENUE = rsd2.getString("stadium");
                                 break;
                         }
                    cd2.close();
                    platd2.close();
                                       System.out.println(""+AwayVENUE); 
                    
                    if(rs.getString("matchType").equals("0")){     
                    v.add(""+AwayVENUE);
                    }
                    if(rs.getString("matchType").equals("1")){     
                    v.add(""+HomeVENUE);
                    }
                    
                    v.add(rs.getString("datetime"));
                   dtm.addRow(v);
                }
            if(check ==0)
            {
                jLabel2.setVisible(true);
            }
            plat.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Match_schedule_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formComponentShown
public void yelool()
{
                  try {
            jLabel2.setVisible(false);
            // TODO add your handling code here:
            
                    String VENUE="";                     
          Connection c2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                    String sql2="";
                    PreparedStatement plat2;
                    sql2 = "select * from clubdetails where Name = ?";     
                    plat2 = c2.prepareStatement(sql2);
                    plat2.setString(1,jLabel1.getText());
                    ResultSet rs2 = plat2.executeQuery();
                         while(rs2.next()){
                                VENUE = rs2.getString("stadium");
                                 break;
                         }
            
                   System.out.println(""+VENUE);
            
             Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from match_details where clubname = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1,jLabel1.getText());
            ResultSet rs = plat.executeQuery();
            
            dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
            int check =0;

                    while(rs.next()){
                    check = 1;
                    java.util.Vector v = new java.util.Vector();
                    v.add(rs.getString("opponent"));
                    String OPPONENT = rs.getString("opponent");
                    
                    if(rs.getString("matchType").equals("0"))
                    {
                    Connection cd2 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                    String sqld2="";
                    PreparedStatement platd2;
                    sqld2 = "select * from clubdetails where Name = ?";     
                    platd2 = cd2.prepareStatement(sqld2);
                    platd2.setString(1,OPPONENT);
                    ResultSet rsd2 = platd2.executeQuery();
                         while(rsd2.next()){
                                VENUE = rsd2.getString("stadium");
                                 break;
                         }
                    }
                    v.add(""+VENUE);
                    v.add(rs.getString("datetime"));
                   dtm.addRow(v);
                }
            if(check ==0)
            {
                jLabel2.setVisible(true);
            }
            plat.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Match_schedule_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Match_schedule_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Match_schedule_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Match_schedule_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Match_schedule_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match_schedule_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    void passValue(String text) {
        jLabel1.setText(text);
    }
}
