/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import Class.ConnectionProvider;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Ehsan
 */
public class Register_page2 extends javax.swing.JFrame {

    private int i;
    private int playerNo;
    private String jst;
    
    
    
    /**
     * Creates new form Register_page2
     */
    public Register_page2() {
        initComponents();
                       Image icon7 = new ImageIcon(this.getClass().getResource("/Logo.jpeg")).getImage();
       this.setIconImage(icon7);
       this.setTitle("Football Manager");
        jLabel26.setVisible(false);
        
    }
    public void my_update(String str) {
		l1.setText(str);
	}
    public void my_update2(int str) {
		Player_no1.setText(""+str);
                
                String data = "" + Player_number_box.getItemAt(Player_number_box.getSelectedIndex());  
                if(!data.equals("NO.")){
                int p = Integer.parseInt(data);
                int q = Integer.parseInt(Player_no1.getText());
                Player_no_remain1.setText(""+ (p-q));
                playerNo = Integer.parseInt(data);
                }
	}
    public String returnClubname() {
		return l1.getText();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        Player_number_box = new javax.swing.JComboBox<>();
        l1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RenewLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Player_no1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        Player_number_box1 = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        Player_no_remain1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (1).png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(44, 46, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FOOTBALL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 620));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Club Details :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 55, 124, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stadium Name ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 114, 99, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Coach Name ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 152, 99, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Coach Salary      $");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 218, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No of Players");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 253, 99, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Players Details Added :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 285, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No of Regular Matcher This Season :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 364, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setToolTipText("Stadium");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 111, 160, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setToolTipText("Coach");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 149, 160, -1));

        jTextField4.setToolTipText("Salary");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, 30));
        jTextField4.getAccessibleContext().setAccessibleDescription("Coach_Salary");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("YES/NO");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 187, -1, -1));

        Player_number_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO.", "2", "3", "4", "5", "6", "7", "8" }));
        Player_number_box.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        Player_number_box.setName("NO."); // NOI18N
        Player_number_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_number_boxActionPerformed(evt);
            }
        });
        jPanel2.add(Player_number_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 251, -1, -1));

        l1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("CSE19");
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 55, 183, 38));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 2, 8, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 362, 78, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Details Add Remain :");
        jLabel11.setToolTipText("");
        jLabel11.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 285, -1, -1));

        jPanel3.setBackground(new java.awt.Color(35, 35, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(620, 620));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Club Details :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 55, 124, 38));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Stadium Name ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 114, 99, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Coach Name ");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 152, 99, -1));

        RenewLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RenewLabel1.setForeground(new java.awt.Color(255, 255, 255));
        RenewLabel1.setText("NonRenewable");
        jPanel3.add(RenewLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 188, 99, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Coach Salary      $");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 218, 110, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No of Players");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 253, 99, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Players Details Added :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 285, -1, -1));

        Player_no1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Player_no1.setForeground(new java.awt.Color(255, 255, 255));
        Player_no1.setText("0");
        jPanel3.add(Player_no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 285, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No of Regular Matcher This Season :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 364, -1, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("Add Match to Calender");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 159, 31));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Arial", 1, 9)); // NOI18N
        jButton6.setText("Upload Logo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 90, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setToolTipText("Stadium");
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 111, 160, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setToolTipText("Stadium");
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 149, 160, -1));

        jTextField6.setToolTipText("Stadium");
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 110, 30));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("YES/NO");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 187, -1, -1));

        Player_number_box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO.", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19" }));
        Player_number_box1.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        Player_number_box1.setName("NO."); // NOI18N
        Player_number_box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_number_box1ActionPerformed(evt);
            }
        });
        jPanel3.add(Player_number_box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 251, -1, -1));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 55, 183, 38));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(5, null, 12, 1));
        jPanel3.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 362, 78, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Details Add Remain :");
        jLabel23.setToolTipText("");
        jLabel23.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 285, -1, -1));

        Player_no_remain1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Player_no_remain1.setForeground(new java.awt.Color(255, 255, 255));
        Player_no_remain1.setText("0");
        Player_no_remain1.setToolTipText("");
        Player_no_remain1.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(Player_no_remain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 285, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Schedule Add Remain:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("2");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Add Players Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 159, 31));

        jButton2.setText("()");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 10, 10));

        jDesktopPane1.setBackground(new java.awt.Color(35, 35, 35));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(110, 90));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(110, 90));

        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 110, 90));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 107, 34));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 110, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 140, 20));

        jButton7.setText("()");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 10, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton4.setText("Done");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 498, 107, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(140, 30, 1096, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
                            String stdium = ""+ jTextField1.getText();
                            String coachName = "" + jTextField3.getText();
                            String club_name = "" + l1.getText();
                            Boolean coachStatus;
                            if(i==0)
                            coachStatus = false;
                            else
                            coachStatus = true;    
                            String coach_Salary = "" +jTextField4.getText();
                            int coachSalary = 0 ;
                             coachSalary = Integer.parseInt(coach_Salary);    
                            int NumberOfPlayer = playerNo;
                            int NumberOfMatches = Integer.parseInt(jst);     
                           Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                           String query = "update clubdetails set stadium = ? , playerNo= ? , MatchNo= ? , photo= ? where Name= ?";
                           String jql = "insert into coach_details (coach, clubName , coach_status , salary) values(?,?,?,?)";
                           PreparedStatement plat1 = c.prepareStatement(query);
                           PreparedStatement plat2 = c.prepareStatement(jql);
                           
                            
                            
                           
                            
                            
                          //InputStream is = null;
//            try {
//               // is = new FileInputStream(new File(filename));
//            } catch (FileNotFoundException ex) {
//                JOptionPane.showMessageDialog(this,"Data genjam inserted");
//            }
                          
                           plat1.setString(1,stdium);
                           plat1.setInt(2,NumberOfPlayer);
                           plat1.setInt(3,NumberOfMatches);
                           plat1.setString(5,club_name);
                           
                           FileInputStream fisdd = null;
                           try{
                               fisdd = new FileInputStream(jLabel26.getText());
                               plat1.setString(4, jLabel26.getText());
                           }
                           catch(Exception e)
                           {
                               JOptionPane.showMessageDialog(this,"Data insert ganjam");
                           }
                           
                          // plat1.setBlob(4, is);
                           
                           plat2.setString(1,coachName);
                           plat2.setString(2,club_name);
                           plat2.setBoolean(3,coachStatus);
                           plat2.setInt(4,coachSalary);
                           
                           plat1.executeUpdate();
                           plat2.executeUpdate();
                           
                          JOptionPane.showMessageDialog(this,"Data inserted");
                         c.close();
                       plat1.close();
                       plat2.close();
                       setVisible(false);
                       Homepage obj = new Homepage();
                       obj.passName(club_name);
                       obj.setVisible(true);
                     }   catch (SQLException ex) {
                           JOptionPane.showMessageDialog(this,"Please Insert All Field");
                     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){  
            RenewLabel1.setText("Renewable");
            i=1;
        }     
        else{
            RenewLabel1.setText("NonRenewable");
            i=0;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void Player_number_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_number_boxActionPerformed
        // TODO add your handling code here:
        String data = "" + Player_number_box.getItemAt(Player_number_box.getSelectedIndex());  
        if(!data.equals("NO.")){
        int p = Integer.parseInt(data);
        int q = Integer.parseInt(Player_no1.getText());
        Player_no_remain1.setText(""+ (p-q));
        playerNo = Integer.parseInt(data);
        }
        else{
            Player_no_remain1.setText("0");
        }
    }//GEN-LAST:event_Player_number_boxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

            
        JFileChooser chooser = new JFileChooser("G:\\fx\\ProjectFinal\\src\\Images", FileSystemView.getFileSystemView());
        chooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif", "gif", "bmp")); 
        //chooser.showOpenDialog(null);
        int result = chooser.showSaveDialog(null);

        File selectedFile = chooser.getSelectedFile();
        String filenamess = selectedFile.getName();

        String path = null;
        Image img;
        Image newimg;
        ImageIcon image ;
        if(result == JFileChooser.APPROVE_OPTION){
            
            path = selectedFile.getAbsolutePath();
            ImageIcon myimg = new ImageIcon(path);
            img = myimg.getImage();
            newimg = img.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
            image = new ImageIcon(newimg);
            jLabel13.setIcon(image);
        }
        jLabel26.setText(""+path);
        jLabel26.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void Player_number_box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_number_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player_number_box1ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
         jst = "" + ((JSpinner)evt.getSource()).getValue();
        Schedule_add obj = new Schedule_add();
        int q = Integer.parseInt(jst);
        int p = obj.passAddedSchedule();
        jLabel25.setText(""+ (q-p));
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Player_Record obj2 = new Player_Record();
        obj2.setVisible(true);
        obj2.passThisPage(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Player_Record obj2 = new Player_Record();
        obj2.passThisPage(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Schedule_add obj = new Schedule_add();
        obj.setVisible(true);
        obj.passClubName(l1.getText());
        int q = 0;
        try
        {
        q = Integer.parseInt(jst);
        }
        catch(Exception e)
        {
            jst = "" + jSpinner1.getValue();
            q = Integer.parseInt(jst); 
        }
        int p = obj.passAddedSchedule();
        jLabel25.setText(""+ (q-p));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Schedule_add obj = new Schedule_add();
        jst = "" + jSpinner1.getValue();
        int q = Integer.parseInt(jst);
        int p = obj.passAddedSchedule();
        jLabel25.setText(""+ (q-p));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Player_no1;
    private javax.swing.JLabel Player_no_remain1;
    private javax.swing.JComboBox<String> Player_number_box;
    private javax.swing.JComboBox<String> Player_number_box1;
    private javax.swing.JLabel RenewLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
    byte[] photo = null;
    String filename=null;
}
