/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.Objects;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ehsan
 */
public class squad_practice extends javax.swing.JFrame {

    /**
     * Creates new form squad_practice
     */
    String Formation;
    private int currentCard = 0;
     private CardLayout cl;

     
    final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
    public squad_practice() {
        initComponents();
        turnOff2();
        
        cl = new CardLayout();
 
        cardPanel.setLayout(cl);
        
        cardPanel.add(jp352, "1");
 
        cardPanel.add(jp41212, "2");
 
        cardPanel.add(jp4231, "3");
 
        cardPanel.add(jp433, "4");
        
        cardPanel.add(jp442, "5");
        
        cardPanel.add(jp541, "6");
        
        
    }
    public void turnOn()
    {
        NAME.setVisible(true);
        POS.setVisible(true);
        AGGE.setVisible(true);
        HEIGHT.setVisible(true);
        SALARY.setVisible(true);
        COUNTRY.setVisible(true);
        CLUB.setVisible(true);
        MKT_VALUE.setVisible(true);
        MKT_VALUE_TEXT.setVisible(true);
        SALARY_TEXT.setVisible(true);
        CARD.setVisible(true);
        CARD_DIV.setVisible(true);
    }
    public void turnOff2()
    {
        NAME.setVisible(false);
        POS.setVisible(false);
        AGGE.setVisible(false);
        HEIGHT.setVisible(false);
        SALARY.setVisible(false);
        COUNTRY.setVisible(false);
        CLUB.setVisible(false);
        MKT_VALUE.setVisible(false);
        MKT_VALUE_TEXT.setVisible(false);
        SALARY_TEXT.setVisible(false);
        CARD.setVisible(false);
        CARD_DIV.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        POS = new javax.swing.JLabel();
        CARD_DIV = new javax.swing.JLabel();
        MKT_VALUE_TEXT = new javax.swing.JLabel();
        AGGE = new javax.swing.JLabel();
        COUNTRY = new javax.swing.JLabel();
        HEIGHT = new javax.swing.JLabel();
        CLUB = new javax.swing.JLabel();
        MKT_VALUE = new javax.swing.JLabel();
        SALARY_TEXT = new javax.swing.JLabel();
        SALARY = new javax.swing.JLabel();
        CARD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name_of_club = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        jp352 = new javax.swing.JPanel();
        CB1 = new javax.swing.JLabel();
        CF2 = new javax.swing.JLabel();
        CB2 = new javax.swing.JLabel();
        CB3 = new javax.swing.JLabel();
        DML1 = new javax.swing.JLabel();
        DML2 = new javax.swing.JLabel();
        RMF = new javax.swing.JLabel();
        LMF = new javax.swing.JLabel();
        AMF = new javax.swing.JLabel();
        CF1 = new javax.swing.JLabel();
        GK = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        jp41212 = new javax.swing.JPanel();
        GK1 = new javax.swing.JLabel();
        CF3 = new javax.swing.JLabel();
        AMF1 = new javax.swing.JLabel();
        LMF1 = new javax.swing.JLabel();
        RMF1 = new javax.swing.JLabel();
        DML4 = new javax.swing.JLabel();
        LB = new javax.swing.JLabel();
        RB = new javax.swing.JLabel();
        CB4 = new javax.swing.JLabel();
        CF4 = new javax.swing.JLabel();
        CB6 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        jp4231 = new javax.swing.JPanel();
        GK2 = new javax.swing.JLabel();
        CF5 = new javax.swing.JLabel();
        LWF = new javax.swing.JLabel();
        RWF = new javax.swing.JLabel();
        AMF2 = new javax.swing.JLabel();
        DML3 = new javax.swing.JLabel();
        DML5 = new javax.swing.JLabel();
        LB1 = new javax.swing.JLabel();
        RB1 = new javax.swing.JLabel();
        CB5 = new javax.swing.JLabel();
        CB8 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        jp433 = new javax.swing.JPanel();
        GK3 = new javax.swing.JLabel();
        CF6 = new javax.swing.JLabel();
        LWF1 = new javax.swing.JLabel();
        RWF1 = new javax.swing.JLabel();
        CMF = new javax.swing.JLabel();
        DML6 = new javax.swing.JLabel();
        DML7 = new javax.swing.JLabel();
        LB2 = new javax.swing.JLabel();
        RB2 = new javax.swing.JLabel();
        CB7 = new javax.swing.JLabel();
        CB10 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        jp541 = new javax.swing.JPanel();
        GK4 = new javax.swing.JLabel();
        LMF2 = new javax.swing.JLabel();
        RMF2 = new javax.swing.JLabel();
        CMF1 = new javax.swing.JLabel();
        DML9 = new javax.swing.JLabel();
        LB3 = new javax.swing.JLabel();
        RB3 = new javax.swing.JLabel();
        CB9 = new javax.swing.JLabel();
        CB11 = new javax.swing.JLabel();
        CF8 = new javax.swing.JLabel();
        CB12 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        jp442 = new javax.swing.JPanel();
        GK5 = new javax.swing.JLabel();
        CF7 = new javax.swing.JLabel();
        LWF2 = new javax.swing.JLabel();
        RWF2 = new javax.swing.JLabel();
        CMF2 = new javax.swing.JLabel();
        DML10 = new javax.swing.JLabel();
        LB4 = new javax.swing.JLabel();
        RB4 = new javax.swing.JLabel();
        CB13 = new javax.swing.JLabel();
        CF9 = new javax.swing.JLabel();
        CB15 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        j2.setText("________________________________");
        jPanel2.add(j2);

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel3.setText("Substitute Bench");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 170, 600));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NAME.setText("Lional Messi");
        jPanel1.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 140, 30));

        POS.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        POS.setText("LWF");
        jPanel1.add(POS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, 20));

        CARD_DIV.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        CARD_DIV.setText("|");
        jPanel1.add(CARD_DIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 20, 50));

        MKT_VALUE_TEXT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        MKT_VALUE_TEXT.setText("Market Value:");
        jPanel1.add(MKT_VALUE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 20));

        AGGE.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AGGE.setText("34 Years old");
        jPanel1.add(AGGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, 20));

        COUNTRY.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COUNTRY.setText("Country");
        jPanel1.add(COUNTRY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 40));

        HEIGHT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        HEIGHT.setText("165 cm");
        jPanel1.add(HEIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, 20));

        CLUB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CLUB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CLUB.setText("Club");
        CLUB.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CLUB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CLUB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(CLUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 100, 20));

        MKT_VALUE.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        MKT_VALUE.setText("5000$");
        jPanel1.add(MKT_VALUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 70, 20));

        SALARY_TEXT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SALARY_TEXT.setText("Salary:");
        jPanel1.add(SALARY_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 60, 20));

        SALARY.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SALARY.setText("120$");
        jPanel1.add(SALARY, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, 20));

        CARD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Player Card.png"))); // NOI18N
        jPanel1.add(CARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 380));

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 20));

        name_of_club.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        name_of_club.setText("Manchester United");
        jPanel1.add(name_of_club, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 270, 600));

        cardPanel.setLayout(new java.awt.CardLayout());

        jp352.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jp352ComponentShown(evt);
            }
        });
        jp352.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB1.setText("Null");
        CB1.setToolTipText("");
        CB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB1MouseClicked(evt);
            }
        });
        jp352.add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 120, 60));

        CF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF2.setText("Null");
        CF2.setToolTipText("");
        CF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF2MouseClicked(evt);
            }
        });
        jp352.add(CF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 60));

        CB2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB2.setText("Null");
        CB2.setToolTipText("");
        CB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB2MouseClicked(evt);
            }
        });
        jp352.add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 110, 60));

        CB3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB3.setText("Null");
        CB3.setToolTipText("");
        CB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB3MouseClicked(evt);
            }
        });
        jp352.add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 100, 60));

        DML1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML1.setText("Null");
        DML1.setToolTipText("");
        DML1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML1MouseClicked(evt);
            }
        });
        jp352.add(DML1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 110, 60));

        DML2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML2.setText("Null");
        DML2.setToolTipText("");
        DML2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML2MouseClicked(evt);
            }
        });
        jp352.add(DML2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 120, 60));

        RMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RMF.setText("Null");
        RMF.setToolTipText("");
        RMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMFMouseClicked(evt);
            }
        });
        jp352.add(RMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 100, 60));

        LMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LMF.setText("Null");
        LMF.setToolTipText("");
        LMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMFMouseClicked(evt);
            }
        });
        jp352.add(LMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 60));

        AMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        AMF.setText("Null");
        AMF.setToolTipText("");
        AMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMFMouseClicked(evt);
            }
        });
        jp352.add(AMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, 60));

        CF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF1.setText("Null");
        CF1.setToolTipText("");
        CF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF1MouseClicked(evt);
            }
        });
        jp352.add(CF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, 60));

        GK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK.setText("Null");
        GK.setToolTipText("");
        GK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GKMouseClicked(evt);
            }
        });
        jp352.add(GK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        f1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                f1ComponentShown(evt);
            }
        });
        jp352.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp352, "card2");

        jp41212.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK1.setText("Messi");
        GK1.setToolTipText("");
        GK1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GK1MouseClicked(evt);
            }
        });
        jp41212.add(GK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        CF3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF3.setText("Messi");
        CF3.setToolTipText("");
        CF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF3MouseClicked(evt);
            }
        });
        jp41212.add(CF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, 60));

        AMF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AMF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        AMF1.setText("Messi");
        AMF1.setToolTipText("");
        AMF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMF1MouseClicked(evt);
            }
        });
        jp41212.add(AMF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, 60));

        LMF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LMF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LMF1.setText("Messi");
        LMF1.setToolTipText("");
        LMF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMF1MouseClicked(evt);
            }
        });
        jp41212.add(LMF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 60));

        RMF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RMF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RMF1.setText("Messi");
        RMF1.setToolTipText("");
        RMF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMF1MouseClicked(evt);
            }
        });
        jp41212.add(RMF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 100, 60));

        DML4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML4.setText("Messi");
        DML4.setToolTipText("");
        DML4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML4MouseClicked(evt);
            }
        });
        jp41212.add(DML4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 120, 60));

        LB.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB.setText("Messi");
        LB.setToolTipText("");
        LB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBMouseClicked(evt);
            }
        });
        jp41212.add(LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 60));

        RB.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB.setText("Messi");
        RB.setToolTipText("");
        RB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBMouseClicked(evt);
            }
        });
        jp41212.add(RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 60));

        CB4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB4.setText("Messi");
        CB4.setToolTipText("");
        CB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB4MouseClicked(evt);
            }
        });
        jp41212.add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 60));

        CF4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF4.setText("Messi");
        CF4.setToolTipText("");
        CF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF4MouseClicked(evt);
            }
        });
        jp41212.add(CF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, 60));

        CB6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB6.setText("Messi");
        CB6.setToolTipText("");
        CB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB6MouseClicked(evt);
            }
        });
        jp41212.add(CB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 120, 60));

        f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        jp41212.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp41212, "card3");

        jp4231.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK2.setText("Messi");
        GK2.setToolTipText("");
        GK2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GK2MouseClicked(evt);
            }
        });
        jp4231.add(GK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        CF5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF5.setText("Messi");
        CF5.setToolTipText("");
        CF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF5MouseClicked(evt);
            }
        });
        jp4231.add(CF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, 60));

        LWF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LWF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LWF.setText("Messi");
        LWF.setToolTipText("");
        LWF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LWFMouseClicked(evt);
            }
        });
        jp4231.add(LWF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 60));

        RWF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RWF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RWF.setText("Messi");
        RWF.setToolTipText("");
        RWF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RWFMouseClicked(evt);
            }
        });
        jp4231.add(RWF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 100, 60));

        AMF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AMF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        AMF2.setText("Messi");
        AMF2.setToolTipText("");
        AMF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMF2MouseClicked(evt);
            }
        });
        jp4231.add(AMF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 100, 60));

        DML3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML3.setText("Messi");
        DML3.setToolTipText("");
        DML3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML3MouseClicked(evt);
            }
        });
        jp4231.add(DML3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 110, 60));

        DML5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML5.setText("Messi");
        DML5.setToolTipText("");
        DML5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML5MouseClicked(evt);
            }
        });
        jp4231.add(DML5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 60));

        LB1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB1.setText("Messi");
        LB1.setToolTipText("");
        LB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB1MouseClicked(evt);
            }
        });
        jp4231.add(LB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 60));

        RB1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB1.setText("Messi");
        RB1.setToolTipText("");
        RB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB1MouseClicked(evt);
            }
        });
        jp4231.add(RB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 60));

        CB5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB5.setText("Messi");
        CB5.setToolTipText("");
        CB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB5MouseClicked(evt);
            }
        });
        jp4231.add(CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 60));

        CB8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB8.setText("Messi");
        CB8.setToolTipText("");
        CB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB8MouseClicked(evt);
            }
        });
        jp4231.add(CB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 120, 60));

        f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        jp4231.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp4231, "card4");

        jp433.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK3.setText("Messi");
        GK3.setToolTipText("");
        GK3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GK3MouseClicked(evt);
            }
        });
        jp433.add(GK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        CF6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF6.setText("Messi");
        CF6.setToolTipText("");
        CF6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF6MouseClicked(evt);
            }
        });
        jp433.add(CF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, 60));

        LWF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LWF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LWF1.setText("Messi");
        LWF1.setToolTipText("");
        LWF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LWF1MouseClicked(evt);
            }
        });
        jp433.add(LWF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 60));

        RWF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RWF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RWF1.setText("Messi");
        RWF1.setToolTipText("");
        RWF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RWF1MouseClicked(evt);
            }
        });
        jp433.add(RWF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, 60));

        CMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CMF.setText("Messi");
        CMF.setToolTipText("");
        CMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMFMouseClicked(evt);
            }
        });
        jp433.add(CMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, 60));

        DML6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML6.setText("Messi");
        DML6.setToolTipText("");
        DML6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML6MouseClicked(evt);
            }
        });
        jp433.add(DML6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 110, 60));

        DML7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML7.setText("Messi");
        DML7.setToolTipText("");
        DML7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML7MouseClicked(evt);
            }
        });
        jp433.add(DML7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 60));

        LB2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB2.setText("Messi");
        LB2.setToolTipText("");
        LB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB2MouseClicked(evt);
            }
        });
        jp433.add(LB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 60));

        RB2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB2.setText("Messi");
        RB2.setToolTipText("");
        RB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB2MouseClicked(evt);
            }
        });
        jp433.add(RB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 110, 60));

        CB7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB7.setText("Messi");
        CB7.setToolTipText("");
        CB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB7MouseClicked(evt);
            }
        });
        jp433.add(CB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 120, 60));

        CB10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB10.setText("Messi");
        CB10.setToolTipText("");
        CB10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB10MouseClicked(evt);
            }
        });
        jp433.add(CB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 120, 60));

        f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        jp433.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp433, "card5");

        jp541.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK4.setText("Messi");
        GK4.setToolTipText("");
        GK4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GK4MouseClicked(evt);
            }
        });
        jp541.add(GK4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        LMF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LMF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LMF2.setText("Messi");
        LMF2.setToolTipText("");
        LMF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMF2MouseClicked(evt);
            }
        });
        jp541.add(LMF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 60));

        RMF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RMF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RMF2.setText("Messi");
        RMF2.setToolTipText("");
        RMF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMF2MouseClicked(evt);
            }
        });
        jp541.add(RMF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 110, 60));

        CMF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CMF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CMF1.setText("Messi");
        CMF1.setToolTipText("");
        CMF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMF1MouseClicked(evt);
            }
        });
        jp541.add(CMF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 120, 60));

        DML9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML9.setText("Messi");
        DML9.setToolTipText("");
        DML9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML9MouseClicked(evt);
            }
        });
        jp541.add(DML9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 60));

        LB3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB3.setText("Messi");
        LB3.setToolTipText("");
        LB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB3MouseClicked(evt);
            }
        });
        jp541.add(LB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 120, 60));

        RB3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB3.setText("Messi");
        RB3.setToolTipText("");
        RB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB3MouseClicked(evt);
            }
        });
        jp541.add(RB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, 60));

        CB9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB9.setText("Messi");
        CB9.setToolTipText("");
        CB9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB9MouseClicked(evt);
            }
        });
        jp541.add(CB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 120, 60));

        CB11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB11.setText("Messi");
        CB11.setToolTipText("");
        CB11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB11MouseClicked(evt);
            }
        });
        jp541.add(CB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 120, 60));

        CF8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF8.setText("Messi");
        CF8.setToolTipText("");
        CF8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF8MouseClicked(evt);
            }
        });
        jp541.add(CF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 60));

        CB12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB12.setText("Messi");
        CB12.setToolTipText("");
        CB12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB12MouseClicked(evt);
            }
        });
        jp541.add(CB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 120, 60));

        f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        jp541.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp541, "card6");

        jp442.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK5.setText("Messi");
        GK5.setToolTipText("");
        GK5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GK5MouseClicked(evt);
            }
        });
        jp442.add(GK5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        CF7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF7.setText("Messi");
        CF7.setToolTipText("");
        CF7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF7MouseClicked(evt);
            }
        });
        jp442.add(CF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 60));

        LWF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LWF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LWF2.setText("Messi");
        LWF2.setToolTipText("");
        LWF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LWF2MouseClicked(evt);
            }
        });
        jp442.add(LWF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 60));

        RWF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RWF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RWF2.setText("Messi");
        RWF2.setToolTipText("");
        RWF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RWF2MouseClicked(evt);
            }
        });
        jp442.add(RWF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 60));

        CMF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CMF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CMF2.setText("Messi");
        CMF2.setToolTipText("");
        CMF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMF2MouseClicked(evt);
            }
        });
        jp442.add(CMF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 60));

        DML10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML10.setText("Messi");
        DML10.setToolTipText("");
        DML10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML10MouseClicked(evt);
            }
        });
        jp442.add(DML10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 120, 60));

        LB4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB4.setText("Messi");
        LB4.setToolTipText("");
        LB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB4MouseClicked(evt);
            }
        });
        jp442.add(LB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 140, 60));

        RB4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB4.setText("Messi");
        RB4.setToolTipText("");
        RB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RB4MouseClicked(evt);
            }
        });
        jp442.add(RB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 100, 60));

        CB13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB13.setText("Messi");
        CB13.setToolTipText("");
        CB13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB13MouseClicked(evt);
            }
        });
        jp442.add(CB13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 60));

        CF9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF9.setText("Messi");
        CF9.setToolTipText("");
        CF9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF9MouseClicked(evt);
            }
        });
        jp442.add(CF9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, 60));

        CB15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB15.setText("Messi");
        CB15.setToolTipText("");
        CB15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB15MouseClicked(evt);
            }
        });
        jp442.add(CB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 120, 60));

        f6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        jp442.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        cardPanel.add(jp442, "card7");

        getContentPane().add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB1MouseClicked
        // TODO add your handling code here:
        
            turnOff2();
                try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CB1.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(squad_practice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CB1MouseClicked

    private void CF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF2MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_CF2MouseClicked

    private void CB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CB2MouseClicked

    private void CB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CB3MouseClicked

    private void DML1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_DML1MouseClicked

    private void DML2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DML2MouseClicked

    private void RMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMFMouseClicked
 // TODO add your handling code here:
    }//GEN-LAST:event_RMFMouseClicked

    private void LMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMFMouseClicked

               // TODO add your handling code here:
    }//GEN-LAST:event_LMFMouseClicked

    private void AMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMFMouseClicked
        
    }//GEN-LAST:event_AMFMouseClicked

    private void CF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF1MouseClicked
        
    }//GEN-LAST:event_CF1MouseClicked

    private void GKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GKMouseClicked
        
       

    }//GEN-LAST:event_GKMouseClicked

    private void GK1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GK1MouseClicked
        

    }//GEN-LAST:event_GK1MouseClicked

    private void CF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF3MouseClicked
        
    }//GEN-LAST:event_CF3MouseClicked

    private void AMF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMF1MouseClicked
        
    }//GEN-LAST:event_AMF1MouseClicked

    private void LMF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMF1MouseClicked
        
    }//GEN-LAST:event_LMF1MouseClicked

    private void RMF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMF1MouseClicked
        
    }//GEN-LAST:event_RMF1MouseClicked

    private void DML4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DML4MouseClicked

    private void LBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBMouseClicked
        
    }//GEN-LAST:event_LBMouseClicked

    private void RBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBMouseClicked

        
    }//GEN-LAST:event_RBMouseClicked

    private void CB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB4MouseClicked

    private void CF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF4MouseClicked
        
    }//GEN-LAST:event_CF4MouseClicked

    private void CB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB6MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB6MouseClicked

    private void GK2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GK2MouseClicked
        

    }//GEN-LAST:event_GK2MouseClicked

    private void CF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF5MouseClicked

    }//GEN-LAST:event_CF5MouseClicked

    private void LWFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LWFMouseClicked
 
    }//GEN-LAST:event_LWFMouseClicked

    private void RWFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RWFMouseClicked
        
    }//GEN-LAST:event_RWFMouseClicked

    private void AMF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMF2MouseClicked
        
    }//GEN-LAST:event_AMF2MouseClicked

    private void DML3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML3MouseClicked
        
    }//GEN-LAST:event_DML3MouseClicked

    private void DML5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML5MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DML5MouseClicked

    private void LB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB1MouseClicked
        
    }//GEN-LAST:event_LB1MouseClicked

    private void RB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB1MouseClicked

    
    }//GEN-LAST:event_RB1MouseClicked

    private void CB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB5MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB5MouseClicked

    private void CB8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB8MouseClicked
        
    }//GEN-LAST:event_CB8MouseClicked

    private void GK3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GK3MouseClicked
        

    }//GEN-LAST:event_GK3MouseClicked

    private void CF6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF6MouseClicked
        
    }//GEN-LAST:event_CF6MouseClicked

    private void LWF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LWF1MouseClicked
        
    }//GEN-LAST:event_LWF1MouseClicked

    private void RWF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RWF1MouseClicked
        
    }//GEN-LAST:event_RWF1MouseClicked

    private void CMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMFMouseClicked
        
    }//GEN-LAST:event_CMFMouseClicked

    private void DML6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML6MouseClicked
        
    }//GEN-LAST:event_DML6MouseClicked

    private void DML7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML7MouseClicked
        
    }//GEN-LAST:event_DML7MouseClicked

    private void LB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB2MouseClicked
        
    }//GEN-LAST:event_LB2MouseClicked

    private void RB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB2MouseClicked

       
    }//GEN-LAST:event_RB2MouseClicked

    private void CB7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB7MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB7MouseClicked

    private void CB10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB10MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB10MouseClicked

    private void GK4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GK4MouseClicked
        

    }//GEN-LAST:event_GK4MouseClicked

    private void LMF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMF2MouseClicked
        
    }//GEN-LAST:event_LMF2MouseClicked

    private void RMF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMF2MouseClicked
        
    }//GEN-LAST:event_RMF2MouseClicked

    private void CMF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMF1MouseClicked
        
    }//GEN-LAST:event_CMF1MouseClicked

    private void DML9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DML9MouseClicked

    private void LB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB3MouseClicked
        
    }//GEN-LAST:event_LB3MouseClicked

    private void RB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB3MouseClicked

        
    }//GEN-LAST:event_RB3MouseClicked

    private void CB9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB9MouseClicked
        
    }//GEN-LAST:event_CB9MouseClicked

    private void CB11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB11MouseClicked
        
    }//GEN-LAST:event_CB11MouseClicked

    private void CF8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF8MouseClicked
        
    }//GEN-LAST:event_CF8MouseClicked

    private void CB12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB12MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CB12MouseClicked

    private void GK5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GK5MouseClicked
        

    }//GEN-LAST:event_GK5MouseClicked

    private void CF7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF7MouseClicked
       
    }//GEN-LAST:event_CF7MouseClicked

    private void LWF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LWF2MouseClicked
        
    }//GEN-LAST:event_LWF2MouseClicked

    private void RWF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RWF2MouseClicked
        
    }//GEN-LAST:event_RWF2MouseClicked

    private void CMF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMF2MouseClicked
       
    }//GEN-LAST:event_CMF2MouseClicked

    private void DML10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML10MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DML10MouseClicked

    private void LB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB4MouseClicked
        
    }//GEN-LAST:event_LB4MouseClicked

    private void RB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RB4MouseClicked

    }//GEN-LAST:event_RB4MouseClicked

    private void CB13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB13MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CB13MouseClicked

    private void CF9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF9MouseClicked

    }//GEN-LAST:event_CF9MouseClicked

    private void CB15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB15MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CB15MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:  
                    cl.show(cardPanel, "" + (currentCard));
                    if(currentCard == 1)
                    {
     Vector<String> substitute= new Vector<>();
     Vector<String> playing11= new Vector<>();
     Vector<String> addsubstitute= new Vector<>();
     
                        int playerNo = 1;
                        int CFID=0;
                        int AMFID=0;
                        int DMLID=0;
                        int LMFID=0;
                        int RMFID=0;
                        int CBID=0;
                        int GKID=0;
                        try {
                            
                            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
                            String sql = "select * from player_details where clubName = ?";
                            PreparedStatement plat = c.prepareStatement(sql);
                            plat.setString(1, name_of_club.getText());
                            ResultSet rs = plat.executeQuery();
                            int check =0;
                            while(rs.next())
                            {
                                 if(rs.getString("market_status").equals("0"))
                                 {   
                                     if( playerNo <= 11)
                                     {
                                         if(rs.getString(4).equals("CF"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(CFID == 0)
                                                    {
                                                        CF1.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else if(CFID == 1)
                                                    {
                                                        CF2.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     CFID++;
                                                }
                                                else
                                                {
                                                    CFID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("AMF"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(AMFID == 0)
                                                    {
                                                        AMF.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     AMFID++;
                                                }
                                                else
                                                {
                                                    AMFID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("DML"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(DMLID == 0)
                                                    {
                                                        DML1.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else if(DMLID == 1)
                                                    {
                                                        DML2.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     DMLID++;
                                                }
                                                else
                                                {
                                                    DMLID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("LMF"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(LMFID == 0)
                                                    {
                                                        LMF.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     LMFID++;
                                                }
                                                else
                                                {
                                                    LMFID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("RMF"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(RMFID == 0)
                                                    {
                                                        RMF.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     RMFID++;
                                                }
                                                else
                                                {
                                                    RMFID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("CB"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(CBID == 0)
                                                    {
                                                        CB1.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else if(CBID == 1)
                                                    {
                                                        CB2.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else if(CBID == 2)
                                                    {
                                                        CB3.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }                                                    
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     CBID++;
                                                }
                                                else
                                                {
                                                    CBID++;
                                                }
                                         }
                                         else if(rs.getString(4).equals("GK"))
                                         {
                                            int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                if(dol == -1 )
                                                {
                                                    if(GKID == 0)
                                                    {
                                                        GK.setText(rs.getString(1));
                                                        playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        playerNo++;
                                                    }
                                                    else
                                                    {
                                                        int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                                        if(pol == -1)
                                                        {
                                                            substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                                        }
                                                    }
                                                     GKID++;
                                                }
                                                else
                                                {
                                                    GKID++;
                                                }
                                         }
                                         else
                                         {
                                              int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                              if(pol == -1)
                                              {
                                                    substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                              }                                             
                                         }
                                     }
                                     else
                                     {
                                              int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                                              if(pol == -1)
                                              {
                                                    substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                              }                                         
                                     }
                                 }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(squad_practice.class.getName()).log(Level.SEVERE, null, ex);
                        }
     Iterator<String> playing11iterate = playing11.iterator();
     Iterator<String> substituteiterate = substitute.iterator();
     while(playing11iterate.hasNext()) {
            System.out.print(playing11iterate.next());
            System.out.print(", ");
      }
         System.out.println("\n");      
                 
      while(substituteiterate.hasNext()) {
          String jst = substituteiterate.next();
            int rol = addsubstitute.indexOf(""+jst);
             if(rol == -1)
             {
                     addsubstitute.add(""+jst);
                     JLabel j = new JLabel();
                    j.setText(""+jst);
                    j.setSize(140, 30);
                    j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                    j.setIcon(userIcon);
                    jPanel2.add(j);
                    Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
             }                           
      }           
        
      
                    }
                    else if(currentCard == 2)
                    {
                        
                    }
                    else if(currentCard == 3)
                    {
                        
                    }
                    else if(currentCard == 4)
                    {
                        
                    }
                    else if(currentCard == 5)
                    {
                        
                    }
                    else
                    {
                        
                    }
    }//GEN-LAST:event_formComponentShown

    private void f1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_f1ComponentShown

    }//GEN-LAST:event_f1ComponentShown

    private void jp352ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jp352ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jp352ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(squad_practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(squad_practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(squad_practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(squad_practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new squad_practice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGGE;
    private javax.swing.JLabel AMF;
    private javax.swing.JLabel AMF1;
    private javax.swing.JLabel AMF2;
    private javax.swing.JLabel CARD;
    private javax.swing.JLabel CARD_DIV;
    private javax.swing.JLabel CB1;
    private javax.swing.JLabel CB10;
    private javax.swing.JLabel CB11;
    private javax.swing.JLabel CB12;
    private javax.swing.JLabel CB13;
    private javax.swing.JLabel CB15;
    private javax.swing.JLabel CB2;
    private javax.swing.JLabel CB3;
    private javax.swing.JLabel CB4;
    private javax.swing.JLabel CB5;
    private javax.swing.JLabel CB6;
    private javax.swing.JLabel CB7;
    private javax.swing.JLabel CB8;
    private javax.swing.JLabel CB9;
    private javax.swing.JLabel CF1;
    private javax.swing.JLabel CF2;
    private javax.swing.JLabel CF3;
    private javax.swing.JLabel CF4;
    private javax.swing.JLabel CF5;
    private javax.swing.JLabel CF6;
    private javax.swing.JLabel CF7;
    private javax.swing.JLabel CF8;
    private javax.swing.JLabel CF9;
    private javax.swing.JLabel CLUB;
    private javax.swing.JLabel CMF;
    private javax.swing.JLabel CMF1;
    private javax.swing.JLabel CMF2;
    private javax.swing.JLabel COUNTRY;
    private javax.swing.JLabel DML1;
    private javax.swing.JLabel DML10;
    private javax.swing.JLabel DML2;
    private javax.swing.JLabel DML3;
    private javax.swing.JLabel DML4;
    private javax.swing.JLabel DML5;
    private javax.swing.JLabel DML6;
    private javax.swing.JLabel DML7;
    private javax.swing.JLabel DML9;
    private javax.swing.JLabel GK;
    private javax.swing.JLabel GK1;
    private javax.swing.JLabel GK2;
    private javax.swing.JLabel GK3;
    private javax.swing.JLabel GK4;
    private javax.swing.JLabel GK5;
    private javax.swing.JLabel HEIGHT;
    private javax.swing.JLabel LB;
    private javax.swing.JLabel LB1;
    private javax.swing.JLabel LB2;
    private javax.swing.JLabel LB3;
    private javax.swing.JLabel LB4;
    private javax.swing.JLabel LMF;
    private javax.swing.JLabel LMF1;
    private javax.swing.JLabel LMF2;
    private javax.swing.JLabel LWF;
    private javax.swing.JLabel LWF1;
    private javax.swing.JLabel LWF2;
    private javax.swing.JLabel MKT_VALUE;
    private javax.swing.JLabel MKT_VALUE_TEXT;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel POS;
    private javax.swing.JLabel RB;
    private javax.swing.JLabel RB1;
    private javax.swing.JLabel RB2;
    private javax.swing.JLabel RB3;
    private javax.swing.JLabel RB4;
    private javax.swing.JLabel RMF;
    private javax.swing.JLabel RMF1;
    private javax.swing.JLabel RMF2;
    private javax.swing.JLabel RWF;
    private javax.swing.JLabel RWF1;
    private javax.swing.JLabel RWF2;
    private javax.swing.JLabel SALARY;
    private javax.swing.JLabel SALARY_TEXT;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp352;
    private javax.swing.JPanel jp41212;
    private javax.swing.JPanel jp4231;
    private javax.swing.JPanel jp433;
    private javax.swing.JPanel jp442;
    private javax.swing.JPanel jp541;
    private javax.swing.JLabel name_of_club;
    // End of variables declaration//GEN-END:variables

    void passValue(String clbName, String Formation) {
        name_of_club.setText(clbName);
        this.Formation = Formation;
        
        if(Formation.equals("3-5-2"))
            currentCard = 1;
        else if(Formation.equals("4-1-2-1-2"))
            currentCard = 2;
        else if(Formation.equals("4-2-3-1"))
            currentCard = 3;
        else if(Formation.equals("4-3-3"))
            currentCard = 4;
        else if(Formation.equals("4-4-2"))
            currentCard = 5;
        else if(Formation.equals("5-4-1"))
            currentCard = 6;
        else
            System.out.println(""+Formation);
    }
}
