/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.util.Collections.list;
import java.util.Iterator;
import java.util.Objects;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ehsan
 */
public class Squad_Formation_page extends javax.swing.JFrame {

    /**
     * Creates new form Squad_Formation_page
     */

     Vector<String> substitute= new Vector<>();
     Vector<String> playing11= new Vector<>();

    public Squad_Formation_page() {
        initComponents();
        CF1.setVisible(false);
        CF2.setVisible(false);
        LWF.setVisible(false);
        RWF.setVisible(false);
        LMF.setVisible(false);
        AMF.setVisible(false);
        RMF.setVisible(false);
        CMF.setVisible(false);
        DML1.setVisible(false);
        DML2.setVisible(false);
        CB1.setVisible(false);
        CB2.setVisible(false);
        CB3.setVisible(false);
        LB.setVisible(false);
        RB.setVisible(false);
        GK.setVisible(false);
        
        NAME.setVisible(false);
        POS.setVisible(false);
        AGGE.setVisible(false);
        HEIGHT.setVisible(false);
        SALARY.setVisible(false);
        COUNTRY.setVisible(false);
        CLUB.setVisible(false);
        MKT_VALUE.setVisible(false);
        MKT_VALUE_TEXT.setVisible(false);
        SALARY_TEXT.setVisible(false);
        CARD.setVisible(false);
        CARD_DIV.setVisible(false);
        turnoff3();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GK = new javax.swing.JLabel();
        CF1 = new javax.swing.JLabel();
        LWF = new javax.swing.JLabel();
        RWF = new javax.swing.JLabel();
        AMF = new javax.swing.JLabel();
        LMF = new javax.swing.JLabel();
        RMF = new javax.swing.JLabel();
        CMF = new javax.swing.JLabel();
        DML2 = new javax.swing.JLabel();
        DML1 = new javax.swing.JLabel();
        LB = new javax.swing.JLabel();
        RB = new javax.swing.JLabel();
        CB3 = new javax.swing.JLabel();
        CB2 = new javax.swing.JLabel();
        CF2 = new javax.swing.JLabel();
        CB1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        POS = new javax.swing.JLabel();
        CARD_DIV = new javax.swing.JLabel();
        MKT_VALUE_TEXT = new javax.swing.JLabel();
        AGGE = new javax.swing.JLabel();
        COUNTRY = new javax.swing.JLabel();
        HEIGHT = new javax.swing.JLabel();
        CLUB = new javax.swing.JLabel();
        MKT_VALUE = new javax.swing.JLabel();
        SALARY_TEXT = new javax.swing.JLabel();
        SALARY = new javax.swing.JLabel();
        CARD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name_of_club = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        GK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        GK.setText("Messi");
        GK.setToolTipText("");
        GK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GKMouseClicked(evt);
            }
        });
        getContentPane().add(GK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 100, 60));

        CF1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF1.setText("Messi");
        CF1.setToolTipText("");
        CF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF1MouseClicked(evt);
            }
        });
        getContentPane().add(CF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, 60));

        LWF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LWF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LWF.setText("Messi");
        LWF.setToolTipText("");
        LWF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LWFMouseClicked(evt);
            }
        });
        getContentPane().add(LWF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 60));

        RWF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RWF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RWF.setText("Messi");
        RWF.setToolTipText("");
        RWF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RWFMouseClicked(evt);
            }
        });
        getContentPane().add(RWF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 90, 60));

        AMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        AMF.setText("Messi");
        AMF.setToolTipText("");
        AMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMFMouseClicked(evt);
            }
        });
        getContentPane().add(AMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 100, 60));

        LMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LMF.setText("Messi");
        LMF.setToolTipText("");
        LMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMFMouseClicked(evt);
            }
        });
        getContentPane().add(LMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 60));

        RMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RMF.setText("Messi");
        RMF.setToolTipText("");
        RMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMFMouseClicked(evt);
            }
        });
        getContentPane().add(RMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 100, 60));

        CMF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CMF.setText("Messi");
        CMF.setToolTipText("");
        CMF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMFMouseClicked(evt);
            }
        });
        getContentPane().add(CMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, 60));

        DML2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML2.setText("Messi");
        DML2.setToolTipText("");
        DML2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML2MouseClicked(evt);
            }
        });
        getContentPane().add(DML2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 120, 60));

        DML1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        DML1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        DML1.setText("Messi");
        DML1.setToolTipText("");
        DML1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DML1MouseClicked(evt);
            }
        });
        getContentPane().add(DML1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 110, 60));

        LB.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        LB.setText("Messi");
        LB.setToolTipText("");
        LB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBMouseClicked(evt);
            }
        });
        getContentPane().add(LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 60));

        RB.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        RB.setText("Messi");
        RB.setToolTipText("");
        RB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBMouseClicked(evt);
            }
        });
        getContentPane().add(RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 100, 60));

        CB3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB3.setText("Messi");
        CB3.setToolTipText("");
        CB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB3MouseClicked(evt);
            }
        });
        getContentPane().add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 100, 60));

        CB2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB2.setText("Messi");
        CB2.setToolTipText("");
        CB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB2MouseClicked(evt);
            }
        });
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 110, 60));

        CF2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CF2.setText("Messi");
        CF2.setToolTipText("");
        CF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CF2MouseClicked(evt);
            }
        });
        getContentPane().add(CF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 90, 60));

        CB1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_male_26px.png"))); // NOI18N
        CB1.setText("Messi");
        CB1.setToolTipText("");
        CB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB1MouseClicked(evt);
            }
        });
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 120, 60));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        j2.setText("________________________________");
        jPanel2.add(j2);

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel3.setText("Substitute Bench");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 170, 600));

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NAME.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NAME.setText("Lional Messi");
        jPanel1.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 140, 30));

        POS.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        POS.setText("LWF");
        jPanel1.add(POS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 20));

        CARD_DIV.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        CARD_DIV.setText("|");
        jPanel1.add(CARD_DIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, 50));

        MKT_VALUE_TEXT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        MKT_VALUE_TEXT.setText("Market Value:");
        jPanel1.add(MKT_VALUE_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 110, 20));

        AGGE.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        AGGE.setText("34 Years old");
        jPanel1.add(AGGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 110, 20));

        COUNTRY.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        COUNTRY.setText("Country");
        jPanel1.add(COUNTRY, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        HEIGHT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        HEIGHT.setText("165 cm");
        jPanel1.add(HEIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 110, 20));

        CLUB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CLUB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CLUB.setText("Club");
        CLUB.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CLUB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        CLUB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(CLUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 100, 20));

        MKT_VALUE.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        MKT_VALUE.setText("5000$");
        jPanel1.add(MKT_VALUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 70, 20));

        SALARY_TEXT.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SALARY_TEXT.setText("Salary:");
        jPanel1.add(SALARY_TEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 20));

        SALARY.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        SALARY.setText("120$");
        jPanel1.add(SALARY, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 70, 20));

        CARD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Player Card.png"))); // NOI18N
        jPanel1.add(CARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 380));

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 20));

        name_of_club.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        name_of_club.setText("Manchester United");
        jPanel1.add(name_of_club, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 310, 600));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngegg (4).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 610));

        setBounds(340, 60, 941, 610);
    }// </editor-fold>//GEN-END:initComponents
    public void turnOn()
    {
        NAME.setVisible(true);
        POS.setVisible(true);
        AGGE.setVisible(true);
        HEIGHT.setVisible(true);
        SALARY.setVisible(true);
        COUNTRY.setVisible(true);
        CLUB.setVisible(true);
        MKT_VALUE.setVisible(true);
        MKT_VALUE_TEXT.setVisible(true);
        SALARY_TEXT.setVisible(true);
        CARD.setVisible(true);
        CARD_DIV.setVisible(true);
    }
    public void turnOff2()
    {
        NAME.setVisible(false);
        POS.setVisible(false);
        AGGE.setVisible(false);
        HEIGHT.setVisible(false);
        SALARY.setVisible(false);
        COUNTRY.setVisible(false);
        CLUB.setVisible(false);
        MKT_VALUE.setVisible(false);
        MKT_VALUE_TEXT.setVisible(false);
        SALARY_TEXT.setVisible(false);
        CARD.setVisible(false);
        CARD_DIV.setVisible(false);
    }
    public void turnOff1()
    {
        CF1.setVisible(false);
        CF2.setVisible(false);
        LWF.setVisible(false);
        RWF.setVisible(false);
        LMF.setVisible(false);
        AMF.setVisible(false);
        RMF.setVisible(false);
        CMF.setVisible(false);
        DML1.setVisible(false);
        DML2.setVisible(false);
        CB1.setVisible(false);
        CB2.setVisible(false);
        CB3.setVisible(false);
        LB.setVisible(false);
        RB.setVisible(false);
        GK.setVisible(false);
    }    
    public void turnoff3()
    {
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
            int CFID = 0;
            int LWFID = 0;
             int RWFID = 0;
             int AMFID = 0;
             int CMFID = 0;
             int LMFID = 0;
             int DMLID = 0;
             int RMFID = 0;
             int RBID = 0;
             int LBID = 0;
            int CBID = 0;
             int GKID = 0;
            int playerNo = 1;
            int sub = 1;
            
                try {
            
            // TODO add your handling code here:
             Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where clubName = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, name_of_club.getText());

            ResultSet rs = plat.executeQuery();
            
            
            int check =0;       

            final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
//                    JScrollPane scrollPane = new JScrollPane(jPanel2);
//                    jPanel2.setLayout(new BoxLayout(jPanel2,BoxLayout.Y_AXIS));
            
            while(rs.next()){
                if(rs.getString("market_status").equals("0")){
                 check = 1;
                if( playerNo <= 11){
                    System.out.println(""+playerNo);
                 if(rs.getString(4).equals("CF"))
                 {
                     if(CFID == 0){
                     CF1.setText(rs.getString(1));
                     CF1.setVisible(true);
                     int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     CFID ++;
                     playerNo++;
                     }
                     else if(CFID == 1){
                     CF2.setText(rs.getString(1));
                     CF2.setVisible(true);
                     int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     CFID ++;
                     playerNo++;
                     }
                     else{
                     CFID ++;
                     int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;  
                     }
                     }
                 }
                 else if(rs.getString(4).equals("LWF"))
                 {
                     if(LWFID == 0){
                         LWFID++;
                     LWF.setText(rs.getString(1));
                     LWF.setVisible(true);
                     int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                        }
                     else{
                       LWFID ++;
                                            int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("RWF"))
                 {
                     if(RWFID == 0){
                         RWFID++;
                     RWF.setText(rs.getString(1));
                     RWF.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                        RWFID ++;
                     int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("AMF"))
                 {
                     if(AMFID==0){
                         AMFID++;
                     AMF.setText(rs.getString(1));
                     AMF.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                        AMFID ++;
                                             int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                     // final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++; 
                     }     
                     }
                 }
                 else if(rs.getString(4).equals("CMF"))
                 {
                     if(CMFID==0){
                         CMFID++;
                     CMF.setText(rs.getString(1));
                     CMF.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                        CMFID ++;
                                             int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }   
                     }
                 }
                 else if(rs.getString(4).equals("DML"))
                 {
                     if(DMLID == 0){
                     DML1.setText(rs.getString(1));
                     DML1.setVisible(true);
                     DMLID ++;
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else if(DMLID == 1){
                         
                     DML2.setText(rs.getString(1));
                     DML2.setVisible(true);
                     DMLID ++;
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     
                     playerNo++;
                     }
                     else{
                      DMLID ++;
                                           int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("LMF"))
                 {
                     if(LMFID==0){
                         LMFID++;
                     LMF.setText(rs.getString(1));
                     LMF.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                         LMFID++;
                         int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                              JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("RMF"))
                 {
                     if(RMFID==0){
                         RMFID++;
                     RMF.setText(rs.getString(1));
                     RMF.setVisible(true);
                     int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                         RMFID++;
                     int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("LB"))
                 {
                     if(LBID ==0){
                         LBID++;
                     LB.setText(rs.getString(1));
                     LB.setVisible(true);
                     int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                         LBID++;
                                              int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                               JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("RB"))
                 {
                     if(RBID == 0){
                         RBID++;
                     RB.setText(rs.getString(1));
                     RB.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                         RBID++;
                                              int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                                               JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                     // final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("CB"))
                 {
                     if(CBID == 0){
                     CB1.setText(rs.getString(1));
                     CB1.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     CBID ++;
                     playerNo++;
                     }
                     else if(CBID == 2){
                     CB2.setText(rs.getString(1));
                     CB2.setVisible(true);
                     CBID ++;
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else if(CBID == 1){
                     CB3.setText(rs.getString(1));
                     CB3.setVisible(true);
                     CBID ++;
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }                     
                     else{
                     CBID ++;
                                          int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                      //final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else if(rs.getString(4).equals("GK"))
                 {
                     if(GKID == 0){
                         GKID++;
                     GK.setText(rs.getString(1));
                     GK.setVisible(true);
                                          int dol = playing11.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(dol == -1){
                     playing11.add(""+rs.getString(1)+"-"+rs.getString(4));
                     }
                     playerNo++;
                     }
                     else{
                         GKID++;
                     int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                      JLabel j = new JLabel();
                      j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                      j.setSize(140, 30);
                      j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                     // final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                      j.setIcon(userIcon);
                      jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                      sub++;
                     }
                     }
                 }
                 else
                 {
                     System.out.println("hello");
                 }                 ;
                }
                else{
                     int pol = substitute.indexOf(""+rs.getString(1)+"-"+rs.getString(4));
                     if(pol == -1){
                     substitute.add(""+rs.getString(1)+"-"+rs.getString(4));
                    JLabel j = new JLabel();
                    j.setText(""+rs.getString(1)+"-"+rs.getString(4));
                    j.setSize(140, 30);
                    j.setFont(new Font("Times New Roman", Font.PLAIN, 18));
                  //  final ImageIcon userIcon = new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/Images/user_male_26px.png")));
                    j.setIcon(userIcon);
                    jPanel2.add(j);
                      Dimension labelDim = new Dimension(100,20);
                      jPanel2.setPreferredSize(labelDim);
                    sub++;            
                  }
                }
              }  
            }
            plat.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
     Iterator<String> playing11iterate = playing11.iterator();
     Iterator<String> substituteiterate = substitute.iterator();
         while(playing11iterate.hasNext()) {
            System.out.print(playing11iterate.next());
            System.out.print(", ");
        }
         System.out.println("\n");      
                 
         while(substituteiterate.hasNext()) {
            System.out.print(substituteiterate.next());
            System.out.print(", ");
        }
                     
    }//GEN-LAST:event_formComponentShown

    private void GKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GKMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, GK.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_GKMouseClicked

    private void CB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB2MouseClicked
        // TODO add your handling code here:
        turnOff2();
                try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CB2.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CB2MouseClicked

    private void CB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB3MouseClicked
        // TODO add your handling code here:
               turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CB3.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CB3MouseClicked

    private void CB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB1MouseClicked
        // TODO add your handling code here:
               turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CB1.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CB1MouseClicked

    private void LBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, LB.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LBMouseClicked

    private void RBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBMouseClicked

       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, RB.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RBMouseClicked

    private void DML2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML2MouseClicked
        // TODO add your handling code here:
               turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, DML2.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DML2MouseClicked

    private void DML1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DML1MouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, DML1.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DML1MouseClicked

    private void CMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CMF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CMFMouseClicked

    private void RMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, RMF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RMFMouseClicked

    private void LMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, LMF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LMFMouseClicked

    private void AMFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, AMF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_AMFMouseClicked

    private void LWFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LWFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, LWF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LWFMouseClicked

    private void RWFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RWFMouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, RWF.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RWFMouseClicked

    private void CF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF2MouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CF2.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CF2MouseClicked

    private void CF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CF1MouseClicked
       turnOff2();
        try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            Connection c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/clubname","root","1960");
            String sql = "select * from player_details where Name = ?";
            PreparedStatement plat = c.prepareStatement(sql);
            plat.setString(1, CF1.getText());
            ResultSet rs = plat.executeQuery();
            
            while(rs.next()){
                    NAME.setText(rs.getString("Name"));
                    COUNTRY.setText(rs.getString("country"));
                    POS.setText(rs.getString("position"));          
                    CLUB.setText(rs.getString("clubName"));                    
                    AGGE.setText(rs.getString("age")+" Years old");
                    HEIGHT.setText(rs.getString("Height")+" cm");
                    SALARY.setText(rs.getString("Salary")+"$");
                    MKT_VALUE.setText(rs.getString("market_price")+"$");
                    
                    turnOn();
                    
                    break;
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Squad_Formation_page.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CF1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Squad_Formation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Squad_Formation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Squad_Formation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Squad_Formation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Squad_Formation_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGGE;
    private javax.swing.JLabel AMF;
    private javax.swing.JLabel CARD;
    private javax.swing.JLabel CARD_DIV;
    private javax.swing.JLabel CB1;
    private javax.swing.JLabel CB2;
    private javax.swing.JLabel CB3;
    private javax.swing.JLabel CF1;
    private javax.swing.JLabel CF2;
    private javax.swing.JLabel CLUB;
    private javax.swing.JLabel CMF;
    private javax.swing.JLabel COUNTRY;
    private javax.swing.JLabel DML1;
    private javax.swing.JLabel DML2;
    private javax.swing.JLabel GK;
    private javax.swing.JLabel HEIGHT;
    private javax.swing.JLabel LB;
    private javax.swing.JLabel LMF;
    private javax.swing.JLabel LWF;
    private javax.swing.JLabel MKT_VALUE;
    private javax.swing.JLabel MKT_VALUE_TEXT;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel POS;
    private javax.swing.JLabel RB;
    private javax.swing.JLabel RMF;
    private javax.swing.JLabel RWF;
    private javax.swing.JLabel SALARY;
    private javax.swing.JLabel SALARY_TEXT;
    private javax.swing.JLabel j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name_of_club;
    // End of variables declaration//GEN-END:variables

    void passValue(String text) {
        name_of_club.setText(text);
    }
}
