/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectfinal;

import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.animation.Animation;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Ehsan
 */
public class squard2_formation extends javax.swing.JFrame {

    /**
     * Creates new form squard2_formation
     */
    squad_practice obj = new squad_practice();
    String clbName ="";
    public squard2_formation() {
        initComponents();
        show(position);
        formation.setText(""+Formation);
    }
    int position = 0;
    String Formation;
    
    public String[] takeimage()
    {
        File f = new File (getClass().getResource("/Images/Formation").getFile());
        String[] Images = f.list();
        return Images;
    }   
    
    public void show(int index)
    {
        String [] Images = takeimage();
        String img = Images[index];
        ImageIcon icon =new ImageIcon(getClass().getResource("/Images/Formation/"+img));
        Image image = icon.getImage().getScaledInstance(IMAGE.getWidth(), IMAGE.getHeight(), Image.SCALE_SMOOTH);
        IMAGE.setIcon(new ImageIcon(image));
        Formation = img.substring(0,img.length()-4);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IMAGE = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        formation = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 62, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IMAGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMAGEMouseClicked(evt);
            }
        });
        jPanel1.add(IMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/prev.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 50, 50));

        formation.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formation.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(formation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gradient-football-field-background_52683-66772.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            new Thread();
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(squard2_formation.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.IMAGE.getX();
        if(p>=1)
        {
            Animacion.Animacion.mover_izquierda(900,200,1,2,IMAGE);
            
        }
        position = position+1;
        if(position>=takeimage().length)
        {
            position = takeimage().length - 1;
            
        }
        show(position);
        formation.setText(""+Formation);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
                        try {
            // TODO add your handling code here:
            new Thread();
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(squard2_formation.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.IMAGE.getX();
        if(p>=1)
        {
            Animacion.Animacion.mover_izquierda(900,200,1,2,IMAGE);
            
        }
                position = position-1;
        if(position<0)
        {
            position = 0;
            
        }
        show(position);
        formation.setText(""+Formation);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void IMAGEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMAGEMouseClicked
        // TODO add your handling code here:
         setVisible(false);
         obj.setVisible(true);
         obj.passValue(clbName,Formation);
    }//GEN-LAST:event_IMAGEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(squard2_formation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(squard2_formation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(squard2_formation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(squard2_formation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new squard2_formation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGE;
    private javax.swing.JLabel formation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void passValue(String text) {
        clbName = text;
    }
}
